package br.com.cru.petshop.views;

import br.com.cru.petshop.controllers.ContaReceberController;
import br.com.cru.petshop.controllers.FormasPagamentoController;
import br.com.cru.petshop.controllers.interfaces.IContaReceberController;
import br.com.cru.petshop.controllers.interfaces.IFormasPagamentoController;
import br.com.cru.petshop.core.Dialog;
import br.com.cru.petshop.exceptions.RequiredFieldException;
import br.com.cru.petshop.models.ContaReceber;
import br.com.cru.petshop.models.FormasPagamento;
import br.com.cru.petshop.validations.Validator;
import java.awt.event.WindowEvent;
import java.util.*;
import java.util.logging.Level;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import org.h2.util.StringUtils;

/**
 *
 * @author jose.antonio
 */
public class NovaContaReceberJFrame extends Dialog {

    private IFormasPagamentoController mFormasPagamentoController;
    private IContaReceberController mContaReceberController;

    private ContaReceber mContaReceber = new ContaReceber();
    
    private int mIdContaReceber;
    
    /**
     * Creates new form NovaContaReceberJFrame
     */
    public NovaContaReceberJFrame() {
        initComponents();
        this.setModal(true);
        //this.setModal(true);
        datePickerDataCredito.setFormats("dd-MM-yyyy");
        
       
    }
    
    public NovaContaReceberJFrame(int mIdContaReceber) {
        initComponents();
        this.mIdContaReceber = mIdContaReceber;
        this.setModal(true);
        
        datePickerDataCredito.setFormats("dd-MM-yyyy");
        
        
    }

    private void CreateOrUpdate(){
        if(this.mIdContaReceber != 0) {
            mContaReceber = this.mContaReceberController.findById(this.mIdContaReceber);
            
            comboFormaPagamento.setSelectedItem(mContaReceber.getFormaPagamento());
            
            datePickerDataCredito.setDate(mContaReceber.getDataCredito());
            txtValor.setText(String.valueOf(mContaReceber.getValor()));
            txtArObservacao.setText(mContaReceber.getObservacao());
            checkCreditoRealizado.setSelected(mContaReceber.isCreditoRealizado());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        paneInformacoes = new javax.swing.JPanel();
        lblTipo = new javax.swing.JLabel();
        lblFormaPagamento = new javax.swing.JLabel();
        lblDataCredito = new javax.swing.JLabel();
        lblValor = new javax.swing.JLabel();
        txtValor = new javax.swing.JTextField();
        lblObservacao = new javax.swing.JLabel();
        scrollObservacao = new javax.swing.JScrollPane();
        txtArObservacao = new javax.swing.JTextArea();
        datePickerDataCredito = new org.jdesktop.swingx.JXDatePicker();
        comboFormaPagamento = new javax.swing.JComboBox<>();
        comboTipo = new javax.swing.JComboBox<>();
        checkCreditoRealizado = new javax.swing.JCheckBox();
        btnSalvar = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Conta a Receber");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        paneInformacoes.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblTipo.setText("Tipo:");

        lblFormaPagamento.setText("Forma Pagamento:");

        lblDataCredito.setText("Data do Crédito:");

        lblValor.setText("Valor:");

        lblObservacao.setText("Observações:");

        txtArObservacao.setColumns(20);
        txtArObservacao.setRows(5);
        scrollObservacao.setViewportView(txtArObservacao);

        comboTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Outras Receitas" }));
        comboTipo.setEnabled(false);

        checkCreditoRealizado.setText("Crédito efetuado?");

        javax.swing.GroupLayout paneInformacoesLayout = new javax.swing.GroupLayout(paneInformacoes);
        paneInformacoes.setLayout(paneInformacoesLayout);
        paneInformacoesLayout.setHorizontalGroup(
            paneInformacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneInformacoesLayout.createSequentialGroup()
                .addGroup(paneInformacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneInformacoesLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(lblObservacao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(scrollObservacao))
                    .addGroup(paneInformacoesLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(paneInformacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblFormaPagamento)
                            .addComponent(lblTipo)
                            .addComponent(lblDataCredito))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(paneInformacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(paneInformacoesLayout.createSequentialGroup()
                                .addGap(0, 2, Short.MAX_VALUE)
                                .addGroup(paneInformacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(comboFormaPagamento, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(comboTipo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(datePickerDataCredito, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 188, Short.MAX_VALUE)
                                .addComponent(lblValor)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(paneInformacoesLayout.createSequentialGroup()
                                .addComponent(checkCreditoRealizado)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        paneInformacoesLayout.setVerticalGroup(
            paneInformacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneInformacoesLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(paneInformacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTipo)
                    .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblValor)
                    .addComponent(comboTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(paneInformacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFormaPagamento)
                    .addComponent(comboFormaPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(paneInformacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(datePickerDataCredito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDataCredito))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkCreditoRealizado)
                .addGap(24, 24, 24)
                .addGroup(paneInformacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollObservacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblObservacao))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnVoltar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSalvar))
                    .addComponent(paneInformacoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(paneInformacoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSalvar)
                    .addComponent(btnVoltar))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

        
    }//GEN-LAST:event_formWindowOpened

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        mContaReceber.setDataCredito(datePickerDataCredito.getDate());
        mContaReceber.setFormaPagamento(new FormasPagamento(Objects.requireNonNull(comboFormaPagamento.getSelectedItem()).toString()));
        mContaReceber.setObservacao(txtArObservacao.getText());
        mContaReceber.setTipoConta(Objects.requireNonNull(comboTipo.getSelectedItem()).toString());
        if(!StringUtils.isNullOrEmpty(txtValor.getText())) mContaReceber.setValor(Double.parseDouble(txtValor.getText()));
        mContaReceber.setCreditoRealizado(checkCreditoRealizado.isSelected());

        try {
            if (Validator.validateForNulls(mContaReceber)) {
                this.mContaReceberController.insertAndUpdate(mContaReceber);
                JOptionPane.showMessageDialog(rootPane, "Operação realizada com sucesso!");
                this.dispose();
            }
        } catch (RequiredFieldException ex) {
            java.util.logging.Logger.getLogger(NovoClienteJFrame.class.getName()).log(Level.SEVERE, null, ex);
            ex.notifyUserWithToast();
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NovoClienteJFrame.class.getName()).log(Level.SEVERE, null, ex);

        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void updateListFormasPagamento() {
        List<FormasPagamento> allFormas = this.mFormasPagamentoController.all();

        DefaultComboBoxModel<FormasPagamento> formas = new DefaultComboBoxModel<>();

        allFormas.forEach((c) -> {
            formas.addElement(c);
        });
        comboFormaPagamento.setModel(formas);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NovaContaReceberJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NovaContaReceberJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NovaContaReceberJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NovaContaReceberJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NovaContaReceberJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalvar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JCheckBox checkCreditoRealizado;
    private javax.swing.JComboBox<FormasPagamento> comboFormaPagamento;
    private javax.swing.JComboBox<String> comboTipo;
    private org.jdesktop.swingx.JXDatePicker datePickerDataCredito;
    private javax.swing.JLabel lblDataCredito;
    private javax.swing.JLabel lblFormaPagamento;
    private javax.swing.JLabel lblObservacao;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JLabel lblValor;
    private javax.swing.JPanel paneInformacoes;
    private javax.swing.JScrollPane scrollObservacao;
    private javax.swing.JTextArea txtArObservacao;
    private javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables

    @Override
    public void onCreate(WindowEvent evt) {
    }

    @Override
    public void onResume(WindowEvent evt) {
        updateListFormasPagamento();
        CreateOrUpdate();
    }

    @Override
    public void onClose(WindowEvent evt) {
        
    }

    @Override
    public void onCreateControllers() {
        this.mFormasPagamentoController = new FormasPagamentoController();
        this.mContaReceberController = new ContaReceberController();
    }

    @Override
    public void onCreateViews() {
        
    }
}
